pipeline {
    agent any

    parameters {
        text(name: 'postgresql_users', defaultValue: """
[
  {
    "name": "appuser",
    "password": "secret123"
  }
]
""")
    }

    stages {
        stage('Run Ansible') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'playbooks/postgre_users.yml',
                        inventory: 'inventary.yml',
                        extraVars: [
                            postgresql_users: readJSON(text: params.postgresql_users)
                        ]
                    )
                }
            }
        }
    }
}
