pipeline {
    agent any

    parameters {
        string(name: 'postgresql_version', defaultValue: '15')
        string(name: 'data_directory', defaultValue: '/etc/postgresql/15/main')
        string(name: 'primary_host', defaultValue: '10.10.10.10')
        string(name: 'primary_port', defaultValue: '5432')
        string(name: 'replication_user', defaultValue: 'replicator')
        password(name: 'replication_password', defaultValue: 'secret')
        text(name: 'pg_hba_rules', defaultValue: "host all all 0.0.0.0/0 md5\nhost replication replicator 10.0.0.0/24 md5")
    }

    stages {
        stage('Run Ansible') {
            steps {
                ansiblePlaybook(
                    playbook: 'playbooks/postgre_remote.yml',
                    inventory: 'inventary.yml',
                    extraVars: [
                        postgresql_version: params.postgresql_version,
                        data_directory: params.data_directory,
                        primary_host: params.primary_host,
                        primary_port: params.primary_port,
                        replication_user: params.replication_user,
                        replication_password: params.replication_password,
                        pg_hba_rules: params.pg_hba_rules.split("\n")
                    ]
                )
            }
        }
    }
}
