pipeline {
    agent any

    parameters {
        string(name: 'backup_file', defaultValue: '/tmp/full_backup.sql.gz')
        string(name: 'data_directory', defaultValue: '/var/lib/postgresql/15/main')
        string(name: 'postgresql_version', defaultValue: '15')
        string(name: 'restore_db', defaultValue: 'gitea')
        booleanParam(name: 'force_reinit', defaultValue: false)
    }

    stages {
        stage('Run Ansible') {
            steps {
                ansiblePlaybook(
                    playbook: 'playbooks/postgre_restore.yml',
                    inventory: 'inventary.yml',
                    extraVars: [
                        backup_file: params.backup_file,
                        data_directory: params.data_directory,
                        postgresql_version: params.postgresql_version,
                        restore_db: params.restore_db,
                        force_reinit: params.force_reinit
                    ]
                )
            }
        }
    }
}
